# Generated by Django 3.1.7 on 2021-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('max_value', models.FloatField(verbose_name='max value')),
                ('min_value', models.FloatField(verbose_name='min value')),
                ('unit', models.CharField(choices=[('m', 'Meter'), ('kg', 'Kilogram'), ('s', 'Second'), ('A', 'Ampere'), ('K', 'Kelvin'), ('mol', 'Mole'), ('Cd', 'Candela')], max_length=30, verbose_name='unit')),
                ('prefix', models.CharField(choices=[('G', 'Giga'), ('M', 'Mega'), ('K', 'Kilo'), ('C', 'Centi'), ('m', 'Milli'), ('micro', 'Micro'), ('n', 'Nano')], max_length=30, null=True, verbose_name='prefix')),
            ],
        ),
    ]
