# Generated by Django 3.1.7 on 2021-03-28 18:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20210328_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('max_value', models.FloatField(verbose_name='max value')),
                ('min_value', models.FloatField(verbose_name='min value')),
                ('unit', models.CharField(choices=[('m', 'Meter'), ('kg', 'Kilogram'), ('s', 'Second'), ('A', 'Ampere'), ('K', 'Kelvin'), ('mol', 'Mole'), ('Cd', 'Candela')], max_length=30, verbose_name='unit')),
                ('prefix', models.CharField(choices=[('G', 'Giga'), ('M', 'Mega'), ('K', 'Kilo'), ('C', 'Centi'), ('m', 'Milli'), ('micro', 'Micro'), ('n', 'Nano')], max_length=30, verbose_name='prefix')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('is_damaged', models.BooleanField(default=False, verbose_name='is damaged')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(validators=[django.core.validators.MaxValueValidator(1.0)], verbose_name='coefficient')),
                ('prefix', models.CharField(choices=[('G', 'Giga'), ('M', 'Mega'), ('K', 'Kilo'), ('C', 'Centi'), ('m', 'Milli'), ('micro', 'Micro'), ('n', 'Nano')], max_length=30, verbose_name='prefix')),
                ('max_value', models.FloatField(verbose_name='max value')),
                ('min_value', models.FloatField(verbose_name='min value')),
                ('possible_deviation', models.FloatField(default=0, verbose_name='possible deviation')),
                ('time_interval', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='time interval')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='freights.device')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='freights.freight')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='freights.rule')),
            ],
        ),
    ]
