# Generated by Django 3.1.7 on 2021-04-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('freights', '0002_auto_20210412_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.device'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
