# Generated by Django 3.1.7 on 2021-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0003_auto_20210412_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='status',
            field=models.CharField(choices=[('not_assigned', 'Not assigned'), ('waiting', 'Waiting'), ('in_delivery_transit', 'In delivery transit'), ('transfering', 'Transfering'), ('in_reception_transit', 'In reception transit'), ('delivered', 'Delivered'), ('returning', 'Returning'), ('returned', 'Returned')], max_length=30, verbose_name='status'),
        ),
    ]
