# Generated by Django 3.1.7 on 2021-03-28 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('type', models.CharField(choices=[('sea', 'Sea'), ('air', 'Air'), ('land', 'land')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('busy', 'Busy'), ('free', 'Free'), ('unavailable', 'Unavailable')], default='free', max_length=30, verbose_name='status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_datetime', models.DateTimeField(verbose_name='arrival datetime')),
                ('delay_time', models.DurationField(default=datetime.timedelta(0), verbose_name='delay time')),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('reception', 'Reception')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_transit', 'In transit'), ('transfering', 'Transfering'), ('waiting', 'Waiting'), ('done', 'Done')], default='done', max_length=30, verbose_name='status')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.robot')),
            ],
        ),
    ]
