# Generated by Django 3.1.7 on 2021-03-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_transit', 'In transit'), ('transfering', 'Transfering'), ('waiting', 'Waiting'), ('done', 'Done')], default='not_started', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_transfer', to='companies.service')),
                ('reception_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_transfer', to='companies.service')),
            ],
        ),
    ]
