# Generated by Django 3.1.7 on 2021-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210328_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_transit_without_freight', 'In transit without freight'), ('in_transit_with_freight', 'In transit with freight'), ('transfering', 'Transfering'), ('waiting', 'Waiting'), ('done', 'Done')], default='not_started', max_length=30, verbose_name='status'),
        ),
    ]
