# Generated by Django 3.1.7 on 2021-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210413_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('third_party', 'Third party'), ('fourth_party', 'Fourth party'), ('distribution', 'Distribution'), ('reverse', 'Reverse')], max_length=30, verbose_name='type'),
        ),
    ]
