# Generated by Django 3.1.7 on 2021-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210417_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='delay_time',
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('waiting', 'Waiting'), ('done', 'Done'), ('in_transit_without_freight', 'In transit without freight'), ('in_transit_with_freight', 'In transit with freight'), ('transfering', 'Transfering'), ('returning_freight', 'Returning freight'), ('returned_freight', 'Returned freight')], default='not_started', max_length=30, verbose_name='status'),
        ),
    ]
